# Generated by Django 2.0.5 on 2018-11-14 11:16

from django.db import migrations, models
import django.db.models.deletion
import guilds.models.rank
import guilds.models.transaction


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInGuildWithRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='RankGuildPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildPerm', models.CharField(choices=[(guilds.models.rank.PermissionType('None'), 'None'), (guilds.models.rank.PermissionType('Read'), 'Read'), (guilds.models.rank.PermissionType('Write'), 'Write'), (guilds.models.rank.PermissionType('Admin'), 'Admin')], default=guilds.models.rank.PermissionType('Read'), max_length=10)),
                ('bankPerm', models.CharField(choices=[(guilds.models.rank.PermissionType('None'), 'None'), (guilds.models.rank.PermissionType('Read'), 'Read'), (guilds.models.rank.PermissionType('Write'), 'Write'), (guilds.models.rank.PermissionType('Admin'), 'Admin')], default=guilds.models.rank.PermissionType('Read'), max_length=10)),
                ('boardPerm', models.CharField(choices=[(guilds.models.rank.PermissionType('None'), 'None'), (guilds.models.rank.PermissionType('Read'), 'Read'), (guilds.models.rank.PermissionType('Write'), 'Write'), (guilds.models.rank.PermissionType('Admin'), 'Admin')], default=guilds.models.rank.PermissionType('Read'), max_length=10)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guilds.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='RankThreadPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadPerm', models.CharField(choices=[(guilds.models.rank.PermissionType('None'), 'None'), (guilds.models.rank.PermissionType('Read'), 'Read'), (guilds.models.rank.PermissionType('Write'), 'Write'), (guilds.models.rank.PermissionType('Admin'), 'Admin')], default=guilds.models.rank.PermissionType('Read'), max_length=10)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(guilds.models.transaction.TransactionType('Money transaction'), 'Money transaction'), (guilds.models.transaction.TransactionType('Reputation transaction'), 'Reputation transaction')], default=guilds.models.transaction.TransactionType('Money transaction'), max_length=10)),
                ('message', models.TextField()),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Character')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Character')),
            ],
        ),
        migrations.AddField(
            model_name='rankthreadpermission',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Thread'),
        ),
        migrations.AddField(
            model_name='content',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild'),
        ),
        migrations.AddField(
            model_name='content',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Thread'),
        ),
        migrations.AddField(
            model_name='characteringuildwithrank',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild'),
        ),
        migrations.AddField(
            model_name='characteringuildwithrank',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Rank'),
        ),
    ]
