# Generated by Django 2.2.4 on 2019-09-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('characterpermissions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.CharacterPermissions')),
            ],
            bases=('permissions.characterpermissions',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='permissions.PermissionManager')),
                ('subjects', models.ManyToManyField(to='base.Character')),
            ],
            options={
                'unique_together': {('name', 'manager')},
            },
        ),
        migrations.AddField(
            model_name='characterpermissions',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.PermissionManager'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.TextField(max_length=30)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.PermissionManager')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Character')),
            ],
            options={
                'unique_together': {('subject', 'permission', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.TextField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.Group')),
            ],
            options={
                'unique_together': {('group', 'permission')},
            },
        ),
    ]
