# Generated by Django 2.2.5 on 2019-09-07 15:00

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', chat.models.LowerCaseCharField(max_length=30, unique=True)),
                ('permission_needed', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
