# Generated by Django 2.2.7 on 2020-01-05 08:43

from django.db import migrations, models

import chat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', chat.models.LowerCaseCharField(max_length=30, unique=True)),
                ('permission_needed', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Místnost',
                'verbose_name_plural': 'Místnosti',
            },
        ),
    ]
