# Generated by Django 2.2.8 on 2019-12-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Místnost', 'verbose_name_plural': 'Místnosti'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='permission_needed',
        ),
    ]
