# Generated by Django 3.1 on 2020-08-23 15:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='message',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
