# Generated by Django 3.0.5 on 2020-05-06 16:12

from django.db import migrations, models
import django.db.models.deletion
import dungeon.fields
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', dungeon.fields.StringIdentifier(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('on_enter', dungeon.fields.LuaField(blank=True, null=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.Dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', dungeon.fields.StringIdentifier(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('on_click', dungeon.fields.LuaField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Click'), (1, 'Text Input')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.Event')),
            ],
        ),
        migrations.AddField(
            model_name='dungeon',
            name='first_event',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dungeon.Event'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique-option-name'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('dungeon', 'name'), name='unique-dungeon-name'),
        ),
    ]
