# Generated by Django 2.2.7 on 2020-01-05 08:43

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový item', max_length=100, verbose_name='Předmět')),
                ('note', models.TextField(null=True, verbose_name='Poznámka')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dictionary.baseitem_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nová příšera', max_length=128, unique=True, verbose_name='Jméno příšery')),
                ('life', models.CharField(max_length=128, null=True, verbose_name='Životaschopnost')),
                ('defense', models.CharField(max_length=128, null=True, verbose_name='Obranné číslo')),
                ('resist', models.SmallIntegerField(default=0, verbose_name='Odolnost')),
                ('fury', models.PositiveSmallIntegerField(default=0, verbose_name='Bojovnost')),
                ('endurance', models.SmallIntegerField(default=0, verbose_name='Vytrvalost')),
                ('inteligence', models.PositiveSmallIntegerField(default=1, verbose_name='Inteligence')),
                ('treasure', models.CharField(blank=True, max_length=128, null=True, verbose_name='Poklad')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Zkušenosti')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Popis')),
                ('note_pj', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Popis pro PJ')),
                ('powers', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Zvláštní schopnosti')),
            ],
            options={
                'verbose_name': 'Příšera',
                'verbose_name_plural': 'Příšery',
            },
        ),
        migrations.CreateModel(
            name='BeastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Příšera', max_length=64, verbose_name='Jméno kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='BeastWeakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='A', max_length=16, verbose_name='Skupina')),
                ('note', models.TextField(null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Zranitelnost',
                'verbose_name_plural': 'Zranitelnosti',
            },
        ),
        migrations.CreateModel(
            name='ProfessionLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField(default=1, verbose_name='Od úrovně')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.BaseProfession', verbose_name='Povolání')),
            ],
            options={
                'verbose_name': 'Povolání - kouzlo omezení',
                'verbose_name_plural': 'Povolání - kouzlo omezení',
            },
        ),
        migrations.CreateModel(
            name='SkillDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Obtížnost')),
            ],
        ),
        migrations.CreateModel(
            name='SkillRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Stupeň')),
                ('trap', models.SmallIntegerField(verbose_name='Past')),
            ],
        ),
        migrations.CreateModel(
            name='SpellDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový obor magie', max_length=64, verbose_name='Obor magie')),
                ('label', models.CharField(default='NO', max_length=4, verbose_name='Zkratka')),
            ],
            options={
                'verbose_name': 'Obor magie',
                'verbose_name_plural': 'Obory magie',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
            },
            bases=('dictionary.baseitem',),
        ),
        migrations.CreateModel(
            name='SpellDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový směr magie', max_length=64, verbose_name='Směr magie')),
                ('correct', models.SmallIntegerField(default=0, verbose_name='Oprava')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie')),
            ],
            options={
                'verbose_name': 'Směr magie',
                'verbose_name_plural': 'Směry magie',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nové kouzlo', max_length=128, unique=True, verbose_name='Jméno kouzla')),
                ('mana', models.CharField(max_length=128, null=True, verbose_name='Mana')),
                ('range', models.CharField(max_length=128, null=True, verbose_name='Dosah')),
                ('scope', models.CharField(max_length=128, null=True, verbose_name='Rozsah')),
                ('cast_time', models.CharField(max_length=128, null=True, verbose_name='Vyvolání')),
                ('duration', models.CharField(max_length=128, null=True, verbose_name='Trvání')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Popis')),
                ('available_for_professions', models.ManyToManyField(through='dictionary.ProfessionLimitation', to='base.BaseProfession', verbose_name='Povolání')),
                ('directions', models.ManyToManyField(to='dictionary.SpellDirection', verbose_name='Obory magie')),
            ],
            options={
                'verbose_name': 'Kouzlo',
                'verbose_name_plural': 'Kouzla',
            },
        ),
        migrations.CreateModel(
            name='SkillPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(verbose_name='Body')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillDifficulty', verbose_name='Obtížnost')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillRank', verbose_name='Stupeň')),
            ],
            options={
                'verbose_name': 'Dovednostní body',
                'verbose_name_plural': 'Dovednostní body',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nová dovednost', max_length=128, unique=True, verbose_name='Jméno dovednosti')),
                ('duration', models.CharField(max_length=128, null=True, verbose_name='Ověřování')),
                ('success_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální úspěch')),
                ('success', markdownx.models.MarkdownxField(null=True, verbose_name='Úspěch')),
                ('failure', markdownx.models.MarkdownxField(null=True, verbose_name='Neúspěch')),
                ('failure_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální neúspěch')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Poznámka')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillDifficulty', verbose_name='Obtížnost')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Stat', verbose_name='Vlastnost')),
            ],
            options={
                'verbose_name': 'Dovednost',
                'verbose_name_plural': 'Dovednosti',
            },
        ),
        migrations.AddField(
            model_name='professionlimitation',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Spell', verbose_name='Kouzlo'),
        ),
        migrations.CreateModel(
            name='BeastMobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.SmallIntegerField(default=0, verbose_name='Pohyblivost')),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast')),
            ],
            options={
                'verbose_name': 'Pohyblivost',
                'verbose_name_plural': 'Pohyblivosti',
            },
        ),
        migrations.CreateModel(
            name='BeastAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg', models.CharField(default='', max_length=128, verbose_name='Útočné číslo')),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast')),
            ],
            options={
                'verbose_name': 'Útočné číslo',
                'verbose_name_plural': 'Útočná čísla',
            },
        ),
        migrations.AddField(
            model_name='beast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BeastCategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='beast',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CreatureSize', verbose_name='Velikost'),
        ),
        migrations.AddField(
            model_name='beast',
            name='weakness',
            field=models.ManyToManyField(to='dictionary.BeastWeakness', verbose_name='Zranitelnost'),
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
                ('mana', models.IntegerField(default=0, verbose_name='Mana')),
                ('spells', models.ManyToManyField(to='dictionary.Spell', verbose_name='Kouzla')),
            ],
            options={
                'verbose_name': 'Artefakt',
                'verbose_name_plural': 'Artefakty',
            },
            bases=('dictionary.baseitem',),
        ),
    ]
