# Generated by Django 2.2 on 2019-04-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dictionary.baseprofession_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ProfessionLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField(default=1)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jméno rasy', max_length=50)),
                ('str_min', models.SmallIntegerField(default=0)),
                ('str_max', models.SmallIntegerField(default=0)),
                ('str_fix', models.SmallIntegerField(default=0)),
                ('dex_min', models.SmallIntegerField(default=0)),
                ('dex_max', models.SmallIntegerField(default=0)),
                ('dex_fix', models.SmallIntegerField(default=0)),
                ('res_min', models.SmallIntegerField(default=0)),
                ('res_max', models.SmallIntegerField(default=0)),
                ('res_fix', models.SmallIntegerField(default=0)),
                ('int_min', models.SmallIntegerField(default=0)),
                ('int_max', models.SmallIntegerField(default=0)),
                ('int_fix', models.SmallIntegerField(default=0)),
                ('cha_min', models.SmallIntegerField(default=0)),
                ('cha_max', models.SmallIntegerField(default=0)),
                ('cha_fix', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New spell', max_length=128)),
                ('mana', models.CharField(max_length=128, null=True)),
                ('range', models.CharField(max_length=32, null=True)),
                ('cast_time', models.CharField(max_length=32, null=True)),
                ('duration', models.CharField(max_length=32, null=True)),
                ('note', models.TextField(null=True)),
                ('available_for_proffesions', models.ManyToManyField(through='dictionary.ProfessionLimitation', to='dictionary.BaseProfession')),
            ],
        ),
        migrations.AddField(
            model_name='professionlimitation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Spell'),
        ),
    ]
