# Generated by Django 2.2.4 on 2019-08-19 13:38

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový item', max_length=100, verbose_name='Předmět')),
                ('note', models.TextField(null=True, verbose_name='Poznámka')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BaseProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Název povolání', max_length=50, verbose_name='Název povolání')),
                ('str_min', models.SmallIntegerField(default=0, verbose_name='Síla minimum')),
                ('str_max', models.SmallIntegerField(default=0, verbose_name='Síla maximum')),
                ('dex_min', models.SmallIntegerField(default=0, verbose_name='Obratnost minimum')),
                ('dex_max', models.SmallIntegerField(default=0, verbose_name='Obratnost maximum')),
                ('res_min', models.SmallIntegerField(default=0, verbose_name='Odolnost minimum')),
                ('res_max', models.SmallIntegerField(default=0, verbose_name='Odolnost maximum')),
                ('int_min', models.SmallIntegerField(default=0, verbose_name='Inteligence minimum')),
                ('int_max', models.SmallIntegerField(default=0, verbose_name='Inteligence maximum')),
                ('cha_min', models.SmallIntegerField(default=0, verbose_name='Charisma minimum')),
                ('cha_max', models.SmallIntegerField(default=0, verbose_name='Charisma maximum')),
                ('hp_start', models.SmallIntegerField(default=0, verbose_name='Počáteční životy')),
                ('hp_dice', models.SmallIntegerField(default=0, verbose_name='Kostka na životy')),
                ('hp_dice_fix', models.SmallIntegerField(default=0, verbose_name='Oprava kostky na životy')),
                ('hp_9', models.SmallIntegerField(default=0, verbose_name='Životy od 9 úrovně')),
                ('parentProf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession', verbose_name='Vychází z povolání')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dictionary.baseprofession_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Povolání',
                'verbose_name_plural': 'Povolání',
            },
        ),
        migrations.CreateModel(
            name='ProfessionLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField(default=1, verbose_name='Od úrovně')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession', verbose_name='Povolání')),
            ],
            options={
                'verbose_name': 'Povolání - kouzlo omezení',
                'verbose_name_plural': 'Povolání - kouzlo omezení',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Název rasy', max_length=50, verbose_name='Název rasy')),
                ('str_min', models.SmallIntegerField(default=0, verbose_name='Síla minimum')),
                ('str_max', models.SmallIntegerField(default=0, verbose_name='Síla maximum')),
                ('str_fix', models.SmallIntegerField(default=0, verbose_name='Síla oprava')),
                ('dex_min', models.SmallIntegerField(default=0, verbose_name='Obratnost minimum')),
                ('dex_max', models.SmallIntegerField(default=0, verbose_name='Obratnost maximum')),
                ('dex_fix', models.SmallIntegerField(default=0, verbose_name='Obratnost oprava')),
                ('res_min', models.SmallIntegerField(default=0, verbose_name='Odolnost minimum')),
                ('res_max', models.SmallIntegerField(default=0, verbose_name='Odolnost maximum')),
                ('res_fix', models.SmallIntegerField(default=0, verbose_name='Odolnost oprava')),
                ('int_min', models.SmallIntegerField(default=0, verbose_name='Inteligence minimum')),
                ('int_max', models.SmallIntegerField(default=0, verbose_name='Inteligence maximum')),
                ('int_fix', models.SmallIntegerField(default=0, verbose_name='Inteligence oprava')),
                ('cha_min', models.SmallIntegerField(default=0, verbose_name='Charisma minimum')),
                ('cha_max', models.SmallIntegerField(default=0, verbose_name='Charisma maximum')),
                ('cha_fix', models.SmallIntegerField(default=0, verbose_name='Charisma oprava')),
            ],
            options={
                'verbose_name': 'Rasa',
                'verbose_name_plural': 'Rasy',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nová dovednost', max_length=128, verbose_name='Jméno dovednosti')),
                ('stat', models.CharField(choices=[('STR', 'Síla'), ('DEX', 'Obratnost'), ('RES', 'Odolnost'), ('INT', 'Inteligence'), ('CHA', 'Charisma')], max_length=20, verbose_name='Vlastnost')),
                ('difficulty', models.CharField(choices=[('EASY', 'Lehká'), ('MEDIUM', 'Střední'), ('HARD', 'Těžká'), ('EXTREME', 'Velmi těžká')], max_length=20, verbose_name='Obtížnost')),
                ('duration', models.CharField(max_length=128, null=True, verbose_name='Ověřování')),
                ('success_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální úspěch')),
                ('success', markdownx.models.MarkdownxField(null=True, verbose_name='Úspěch')),
                ('failure', markdownx.models.MarkdownxField(null=True, verbose_name='Neúspěch')),
                ('failure_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální neúspěch')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Dovednost',
                'verbose_name_plural': 'Dovednosti',
            },
        ),
        migrations.CreateModel(
            name='SkillRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Obtížnost')),
                ('trap', models.SmallIntegerField(verbose_name='Past')),
            ],
        ),
        migrations.CreateModel(
            name='SpellDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový obor magie', max_length=64, verbose_name='Obor magie')),
                ('label', models.CharField(default='NO', max_length=4, verbose_name='Zkratka')),
            ],
            options={
                'verbose_name': 'Obor magie',
                'verbose_name_plural': 'Obory magie',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
            },
            bases=('dictionary.baseitem',),
        ),
        migrations.CreateModel(
            name='XPLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0, verbose_name='Úroveň')),
                ('xp_needed', models.IntegerField(default=0, verbose_name='Zkušenosti')),
                ('money_needed', models.IntegerField(default=0, verbose_name='Cena')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession')),
            ],
            options={
                'verbose_name': 'Úroveň',
                'verbose_name_plural': 'Úrovně',
            },
        ),
        migrations.CreateModel(
            name='SpellDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový směr magie', max_length=64, verbose_name='Směr magie')),
                ('correct', models.SmallIntegerField(default=0, verbose_name='Oprava')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie')),
            ],
            options={
                'verbose_name': 'Směr magie',
                'verbose_name_plural': 'Směry magie',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nové kouzlo', max_length=128, verbose_name='Jméno kouzla')),
                ('mana', models.CharField(max_length=128, null=True, verbose_name='Mana')),
                ('range', models.CharField(max_length=128, null=True, verbose_name='Dosah')),
                ('scope', models.CharField(max_length=128, null=True, verbose_name='Rozsah')),
                ('cast_time', models.CharField(max_length=128, null=True, verbose_name='Vyvolání')),
                ('duration', models.CharField(max_length=128, null=True, verbose_name='Trvání')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Popis')),
                ('available_for_professions', models.ManyToManyField(through='dictionary.ProfessionLimitation', to='dictionary.BaseProfession', verbose_name='Pro povolání')),
                ('directions', models.ManyToManyField(to='dictionary.SpellDirection', verbose_name='Obory magie')),
            ],
            options={
                'verbose_name': 'Kouzlo',
                'verbose_name_plural': 'Kouzla',
            },
        ),
        migrations.CreateModel(
            name='SkillPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', 'Lehká'), ('MEDIUM', 'Střední'), ('HARD', 'Těžká'), ('EXTREME', 'Velmi těžká')], max_length=20, verbose_name='Obtížnost')),
                ('points', models.SmallIntegerField(verbose_name='Body')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillRank', verbose_name='Stupeň')),
            ],
            options={
                'verbose_name': 'Dovednostní body',
                'verbose_name_plural': 'Dovednostní body',
            },
        ),
        migrations.AddField(
            model_name='professionlimitation',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Spell', verbose_name='Kouzlo'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Category', verbose_name='Nadkategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.AddField(
            model_name='baseitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.Category', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dictionary.baseitem_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
                ('mana', models.IntegerField(default=0, verbose_name='Mana')),
                ('spells', models.ManyToManyField(to='dictionary.Spell', verbose_name='Kouzla')),
            ],
            options={
                'verbose_name': 'Artefakt',
                'verbose_name_plural': 'Artefakty',
            },
            bases=('dictionary.baseitem',),
        ),
    ]
