# Generated by Django 2.2.8 on 2020-02-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beastcategory',
            options={'ordering': ['name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='beastweakness',
            options={'ordering': ['group'], 'verbose_name': 'Zranitelnost', 'verbose_name_plural': 'Zranitelnosti'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Předmět', 'verbose_name_plural': 'Předměty'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name', 'stat'], 'verbose_name': 'Dovednost', 'verbose_name_plural': 'Dovednosti'},
        ),
    ]
