# Generated by Django 2.2.4 on 2019-08-19 13:41

from django.db import migrations

from dictionary.models import race, profession, spell, skill


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(race.initialize_races),
        migrations.RunPython(profession.init_professions),
        migrations.RunPython(spell.initialize_spell_directions),
        migrations.RunPython(skill.init_skills),
    ]
