# Generated by Django 2.2.4 on 2019-09-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_init_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
