# Generated by Django 2.2 on 2019-04-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20190419_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Rasa', 'verbose_name_plural': 'Rasy'},
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='name',
            field=models.CharField(default='Název povolání', max_length=50, verbose_name='Název povolání'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='parentProf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession'),
        ),
        migrations.AlterField(
            model_name='race',
            name='cha_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Charisma oprava'),
        ),
        migrations.AlterField(
            model_name='race',
            name='cha_max',
            field=models.SmallIntegerField(default=0, verbose_name='Charisma maximum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='cha_min',
            field=models.SmallIntegerField(default=0, verbose_name='Charisma minimum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dex_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Obratnost oprava'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dex_max',
            field=models.SmallIntegerField(default=0, verbose_name='Obratnost maximum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dex_min',
            field=models.SmallIntegerField(default=0, verbose_name='Obratnost minimum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='int_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Inteligence oprava'),
        ),
        migrations.AlterField(
            model_name='race',
            name='int_max',
            field=models.SmallIntegerField(default=0, verbose_name='Inteligence maximum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='int_min',
            field=models.SmallIntegerField(default=0, verbose_name='Inteligence minimum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='Název rasy', max_length=50, verbose_name='Název rasy'),
        ),
        migrations.AlterField(
            model_name='race',
            name='res_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Odolnost oprava'),
        ),
        migrations.AlterField(
            model_name='race',
            name='res_max',
            field=models.SmallIntegerField(default=0, verbose_name='Odolnost maximum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='res_min',
            field=models.SmallIntegerField(default=0, verbose_name='Odolnost minimum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Síla oprava'),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_max',
            field=models.SmallIntegerField(default=0, verbose_name='Síla maximum'),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_min',
            field=models.SmallIntegerField(default=0, verbose_name='Síla minimum'),
        ),
    ]
