# Generated by Django 2.2.5 on 2019-10-22 18:12

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0003_auto_20190902_1644'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nová příšera', max_length=128, verbose_name='Jméno příšery')),
                ('live', models.CharField(max_length=128, null=True, verbose_name='Životaschopnost')),
                ('defense', models.CharField(max_length=128, null=True, verbose_name='Obranné číslo')),
                ('resist', models.SmallIntegerField(default=0, verbose_name='Odolnost')),
                ('fury', models.PositiveSmallIntegerField(default=0, verbose_name='Bojovnost')),
                ('endurance', models.SmallIntegerField(default=0, verbose_name='Vytrvalost')),
                ('inteligence', models.PositiveSmallIntegerField(default=1, verbose_name='Inteligence')),
                ('treasure', models.CharField(max_length=128, null=True, verbose_name='Poklad')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Zkušenosti')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Popis')),
                ('note_pj', markdownx.models.MarkdownxField(null=True, verbose_name='Popis pro PJ')),
                ('powers', markdownx.models.MarkdownxField(null=True, verbose_name='Zvláštní schopnosti')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Příšera', max_length=64, verbose_name='Jméno kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='CreatureSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A', max_length=8, unique=True, verbose_name='Velikost')),
            ],
            options={
                'verbose_name': 'Velikostní třída',
                'verbose_name_plural': 'Velikostní třídy',
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='A', max_length=16, verbose_name='Skupina')),
                ('note', models.TextField(null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Zranitelnost',
                'verbose_name_plural': 'Zranitelnosti',
            },
        ),
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.SmallIntegerField(default=0, verbose_name='Pohyblivost')),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast')),
            ],
            options={
                'verbose_name': 'Pohyblivost',
                'verbose_name_plural': 'Pohyblivosti',
            },
        ),
        migrations.AddField(
            model_name='beast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Category'),
        ),
        migrations.AddField(
            model_name='beast',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.CreatureSize'),
        ),
        migrations.AddField(
            model_name='beast',
            name='weakness',
            field=models.ManyToManyField(to='dictionary.Weakness'),
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg', models.CharField(default=0, max_length=128, verbose_name='Útočné číslo')),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast')),
            ],
            options={
                'verbose_name': 'Útočné číslo',
                'verbose_name_plural': 'Útočná čísla',
            },
        ),
    ]
