# Generated by Django 2.2.5 on 2019-10-22 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0004_auto_20191022_2012'),
    ]
    
    operations = [
        # migrations.RunPython(beast.init_weakness),
        # migrations.RunPython(sizes.init_creature_size),
        # migrations.RunPython(beast.init_category)
    ]
