# Generated by Django 2.2 on 2019-04-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20190420_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprofession',
            options={'verbose_name': 'Povolání', 'verbose_name_plural': 'Povolání'},
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='cha_max',
            field=models.SmallIntegerField(default=0, verbose_name='Charisma maximum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='cha_min',
            field=models.SmallIntegerField(default=0, verbose_name='Charisma minimum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='dex_max',
            field=models.SmallIntegerField(default=0, verbose_name='Obratnost maximum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='dex_min',
            field=models.SmallIntegerField(default=0, verbose_name='Obratnost minimum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='hp_9',
            field=models.SmallIntegerField(default=0, verbose_name='Životy od 9 úrovně'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='hp_dice',
            field=models.SmallIntegerField(default=0, verbose_name='Kostka na životy'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='hp_dice_fix',
            field=models.SmallIntegerField(default=0, verbose_name='Oprava kostky na životy'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='hp_start',
            field=models.SmallIntegerField(default=0, verbose_name='Počáteční životy'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='int_max',
            field=models.SmallIntegerField(default=0, verbose_name='Inteligence maximum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='int_min',
            field=models.SmallIntegerField(default=0, verbose_name='Inteligence minimum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='res_max',
            field=models.SmallIntegerField(default=0, verbose_name='Odolnost maximum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='res_min',
            field=models.SmallIntegerField(default=0, verbose_name='Odolnost minimum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='str_max',
            field=models.SmallIntegerField(default=0, verbose_name='Síla maximum'),
        ),
        migrations.AddField(
            model_name='baseprofession',
            name='str_min',
            field=models.SmallIntegerField(default=0, verbose_name='Síla minimum'),
        ),
        migrations.AlterField(
            model_name='baseprofession',
            name='parentProf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession'),
        ),
        migrations.CreateModel(
            name='XPLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0, verbose_name='Úroveň')),
                ('xp_needed', models.IntegerField(default=0, verbose_name='Zkušenosti')),
                ('money_needed', models.IntegerField(default=0, verbose_name='Cena')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession')),
            ],
            options={
                'verbose_name': 'Úroveň',
                'verbose_name_plural': 'Úrovně',
            },
        ),
    ]
