# Generated by Django 2.2.5 on 2019-10-26 10:00

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0005_auto_20191022_2016'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='SkillDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Obtížnost')),
            ],
        ),
        migrations.AlterModelOptions(
            name='beast',
            options={'verbose_name': 'Příšera', 'verbose_name_plural': 'Příšery'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='skillpoints',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='beast',
            name='note_pj',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Popis pro PJ'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='powers',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Zvláštní schopnosti'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='treasure',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Poklad'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='weakness',
            field=models.ManyToManyField(to='dictionary.Weakness', verbose_name='Zranitelnost'),
        ),
        migrations.AlterField(
            model_name='skillrank',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Stupeň'),
        ),
    ]
