# Generated by Django 2.2 on 2019-04-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20190420_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='available_for_proffesions',
            new_name='available_for_professions',
        ),
    ]
