# Generated by Django 2.2.5 on 2019-10-26 11:43

from django.db import migrations

from dictionary.models import skill


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0006_auto_20191026_1200'),
    ]
    
    operations = [
        migrations.RunPython(skill.init_ranks_and_difficulty),
    ]
