# Generated by Django 2.2.5 on 2019-10-26 11:45

import django.db.models.deletion
from django.db import migrations, models

from dictionary.models import skill


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0007_auto_20191026_1343'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='skill',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillDifficulty', verbose_name='Obtížnost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillpoints',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillDifficulty', verbose_name='Obtížnost'),
            preserve_default=False,
        ),
        migrations.RunPython(skill.init_skills),
    ]
