# Generated by Django 2.2 on 2019-04-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dictionary', '0007_auto_20190420_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový item', max_length=100, verbose_name='Předmět')),
                ('note', models.TextField(null=True, verbose_name='Poznámka')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dictionary.baseitem_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='professionlimitation',
            options={'verbose_name': 'Povolání - kouzlo omezení', 'verbose_name_plural': 'Povolání - kouzlo omezení'},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'verbose_name': 'Kouzlo', 'verbose_name_plural': 'Kouzla'},
        ),
        migrations.AlterField(
            model_name='baseprofession',
            name='parentProf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession', verbose_name='Vychází z povolání'),
        ),
        migrations.AlterField(
            model_name='professionlimitation',
            name='from_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Od úrovně'),
        ),
        migrations.AlterField(
            model_name='professionlimitation',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession', verbose_name='Povolání'),
        ),
        migrations.AlterField(
            model_name='professionlimitation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Spell', verbose_name='Kouzlo'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cast_time',
            field=models.CharField(max_length=32, null=True, verbose_name='Vyvolání'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=32, null=True, verbose_name='Trvání'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='mana',
            field=models.CharField(max_length=128, null=True, verbose_name='Mana'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(default='New spell', max_length=128, verbose_name='Jméno kouzla'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='note',
            field=models.TextField(null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=32, null=True, verbose_name='Dosah'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
            },
            bases=('dictionary.baseitem',),
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.BaseItem')),
                ('mana', models.IntegerField(default=0, verbose_name='Mana')),
                ('spells', models.ManyToManyField(to='dictionary.Spell', verbose_name='Kouzla')),
            ],
            options={
                'verbose_name': 'Artefakt',
                'verbose_name_plural': 'Artefakty',
            },
            bases=('dictionary.baseitem',),
        ),
    ]
