# Generated by Django 2.2.5 on 2019-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0008_auto_20191026_1345'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='stat',
        ),
    ]
