# Generated by Django 2.2 on 2019-04-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20190421_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionlimitation',
            old_name='skill',
            new_name='spell',
        ),
    ]
