# Generated by Django 2.2.5 on 2019-10-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_auto_20191026_1524'),
        ('dictionary', '0009_remove_skill_stat'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='skill',
            name='stat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Stat', verbose_name='Vlastnost'),
            preserve_default=False,
        ),
    ]
