# Generated by Django 2.2 on 2019-05-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20190424_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový obor magie', max_length=64, verbose_name='Název oboru magie')),
                ('label', models.CharField(default='NO', max_length=4, verbose_name='Zkratka')),
            ],
            options={
                'verbose_name': 'Obor magie',
                'verbose_name_plural': 'Obory magie',
            },
        ),
        migrations.AddField(
            model_name='spell',
            name='scope',
            field=models.CharField(max_length=32, null=True, verbose_name='Rozsah'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(default='Nové kouzlo', max_length=128, verbose_name='Jméno kouzla'),
        ),
        migrations.AddField(
            model_name='spell',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie'),
        ),
    ]
