# Generated by Django 2.2.5 on 2019-10-26 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0010_skill_stat'),
    ]
    
    operations = [
        migrations.RenameField(
            model_name='beast',
            old_name='live',
            new_name='life',
        ),
    ]
