# Generated by Django 2.2 on 2019-05-01 09:44

from django.db import migrations

from dictionary.models import spell


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20190501_1131'),
    ]

    operations = [
        migrations.RunPython(spell.initialize_spell_disciplines),
    ]
