# Generated by Django 2.2.7 on 2019-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0011_auto_20191026_2015'),
    ]
    
    operations = [
        migrations.RenameField(
            model_name='baseprofession',
            old_name='parentProf',
            new_name='parent_prof',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Nová dovednost', max_length=128, unique=True, verbose_name='Jméno dovednosti'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='available_for_professions',
            field=models.ManyToManyField(through='dictionary.ProfessionLimitation', to='dictionary.BaseProfession', verbose_name='Povolání'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(default='Nové kouzlo', max_length=128, unique=True, verbose_name='Jméno kouzla'),
        ),
    ]
