# Generated by Django 2.2 on 2019-05-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20190501_1144'),
    ]

    operations = [
    ]
