# Generated by Django 2.2 on 2019-05-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20190501_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='cast_time',
            field=models.CharField(max_length=128, null=True, verbose_name='Vyvolání'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=128, null=True, verbose_name='Trvání'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=128, null=True, verbose_name='Dosah'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='scope',
            field=models.CharField(max_length=128, null=True, verbose_name='Rozsah'),
        ),
    ]
