# Generated by Django 2.2.7 on 2019-11-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0012_auto_20191114_1728'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='BeastAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg', models.CharField(default='', max_length=128, verbose_name='Útočné číslo')),
            ],
            options={
                'verbose_name': 'Útočné číslo',
                'verbose_name_plural': 'Útočná čísla',
            },
        ),
        migrations.CreateModel(
            name='BeastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Příšera', max_length=64, verbose_name='Jméno kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='BeastMobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.SmallIntegerField(default=0, verbose_name='Pohyblivost')),
            ],
            options={
                'verbose_name': 'Pohyblivost',
                'verbose_name_plural': 'Pohyblivosti',
            },
        ),
        migrations.CreateModel(
            name='BeastWeakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='A', max_length=16, verbose_name='Skupina')),
                ('note', models.TextField(null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Zranitelnost',
                'verbose_name_plural': 'Zranitelnosti',
            },
        ),
        migrations.RemoveField(
            model_name='attack',
            name='beast',
        ),
        migrations.RemoveField(
            model_name='mobility',
            name='beast',
        ),
        migrations.AlterField(
            model_name='beast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.BeastCategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='name',
            field=models.CharField(default='Nová příšera', max_length=128, unique=True, verbose_name='Jméno příšery'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.CreatureSize', verbose_name='Velikost'),
        ),
        migrations.AlterField(
            model_name='beast',
            name='weakness',
            field=models.ManyToManyField(to='dictionary.BeastWeakness', verbose_name='Zranitelnost'),
        ),
        migrations.DeleteModel(
            name='Attack',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Mobility',
        ),
        migrations.DeleteModel(
            name='Weakness',
        ),
        migrations.AddField(
            model_name='beastmobility',
            name='beast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast'),
        ),
        migrations.AddField(
            model_name='beastattack',
            name='beast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Beast'),
        ),
    ]
