# Generated by Django 2.2.7 on 2019-11-14 17:00

from django.db import migrations

from dictionary.models import beast, sizes


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0013_auto_20191114_1730'),
    ]
    
    operations = [
        migrations.RunPython(beast.init_weakness),
        migrations.RunPython(sizes.init_creature_size),
        migrations.RunPython(beast.init_category)
    ]
