# Generated by Django 2.2 on 2019-05-05 09:27

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20190504_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Předmět', 'ITEM'), ('Nestvůra', 'BEAST')], max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='note',
            field=markdownx.models.MarkdownxField(null=True, verbose_name='Popis'),
        ),
    ]
