# Generated by Django 2.2 on 2019-06-13 12:56

import markdownx.models
from django.db import migrations, models

import base.models.stat
import dictionary.models.skill


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20190505_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nová dovednost', max_length=128, verbose_name='Jméno dovednosti')),
                ('stat', models.CharField(choices=[(base.models.stat.Stat('Síla'), 'Síla'), (base.models.stat.Stat('Obratnost'), 'Obratnost'), (base.models.stat.Stat('Odolnost'), 'Odolnost'), (base.models.stat.Stat('Inteligence'), 'Inteligence'), (base.models.stat.Stat('Charisma'), 'Charisma')], max_length=20, verbose_name='Vlastnost')),
                ('difficulty', models.CharField(choices=[(dictionary.models.skill.SkillDifficulty('Lehká'), 'Lehká'), (dictionary.models.skill.SkillDifficulty('Střední'), 'Střední'), (dictionary.models.skill.SkillDifficulty('Těžká'), 'Těžká'), (dictionary.models.skill.SkillDifficulty('Velmi těžká'), 'Velmi těžká')], max_length=20, verbose_name='Obtížnost')),
                ('duration', models.CharField(max_length=128, null=True, verbose_name='Ověřování')),
                ('success_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální úspěch')),
                ('success', markdownx.models.MarkdownxField(null=True, verbose_name='Úspěch')),
                ('failure', markdownx.models.MarkdownxField(null=True, verbose_name='Neúspěch')),
                ('failure_total', markdownx.models.MarkdownxField(null=True, verbose_name='Totální neúspěch')),
                ('note', markdownx.models.MarkdownxField(null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Dovednost',
                'verbose_name_plural': 'Dovednosti',
            },
        ),
    ]
