# Generated by Django 2.2 on 2019-06-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nový směr magie', max_length=64, verbose_name='Název směru magie')),
                ('correct', models.SmallIntegerField(default=0, verbose_name='Oprava')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie')),
            ],
            options={
                'verbose_name': 'Směr magie',
                'verbose_name_plural': 'Směry magie',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='discipline',
        ),
        migrations.AlterField(
            model_name='skill',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Lehká'), ('MEDIUM', 'Střední'), ('HARD', 'Těžká'), ('SUPER_HARD', 'Velmi těžká')], max_length=20, verbose_name='Obtížnost'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stat',
            field=models.CharField(choices=[('STR', 'Síla'), ('DEX', 'Obratnost'), ('RES', 'Odolnost'), ('INT', 'Inteligence'), ('CHA', 'Charisma')], max_length=20, verbose_name='Vlastnost'),
        ),
        migrations.CreateModel(
            name='SpellDisciplineLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.ManyToManyField(to='dictionary.SpellDirection')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SpellDiscipline', verbose_name='Obor magie')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Spell', verbose_name='Kouzlo')),
            ],
            options={
                'verbose_name': 'Koulo - obor - směry magie',
                'verbose_name_plural': 'Koulo - obor - směry magie',
            },
        ),
        migrations.AddField(
            model_name='spell',
            name='disciplines',
            field=models.ManyToManyField(through='dictionary.SpellDisciplineLimitation', to='dictionary.SpellDiscipline', verbose_name='Obory magie'),
        ),
    ]
