# Generated by Django 2.2.3 on 2019-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20190623_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='spell',
            name='directions',
            field=models.ManyToManyField(to='dictionary.SpellDirection', verbose_name='Směry magie'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='available_for_professions',
            field=models.ManyToManyField(through='dictionary.ProfessionLimitation', to='dictionary.BaseProfession', verbose_name='Pro povolání'),
        ),
        migrations.DeleteModel(
            name='SpellDisciplineLimitation',
        ),
    ]
