# Generated by Django 2.2 on 2019-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_auto_20190726_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='directions',
            field=models.ManyToManyField(to='dictionary.SpellDirection', verbose_name='Obory magie'),
        ),
    ]
