# Generated by Django 2.2.4 on 2019-08-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0020_auto_20190803_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Obtížnost')),
                ('trap', models.SmallIntegerField(verbose_name='Past')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Lehká'), ('MEDIUM', 'Střední'), ('HARD', 'Těžká'), ('EXTREME', 'Velmi těžká')], max_length=20, verbose_name='Obtížnost'),
        ),
        migrations.AlterField(
            model_name='spelldirection',
            name='name',
            field=models.CharField(default='Nový směr magie', max_length=64, verbose_name='Směr magie'),
        ),
        migrations.AlterField(
            model_name='spelldiscipline',
            name='name',
            field=models.CharField(default='Nový obor magie', max_length=64, verbose_name='Obor magie'),
        ),
        migrations.CreateModel(
            name='SkillPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', 'Lehká'), ('MEDIUM', 'Střední'), ('HARD', 'Těžká'), ('EXTREME', 'Velmi těžká')], max_length=20, verbose_name='Obtížnost')),
                ('points', models.SmallIntegerField(verbose_name='Body')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SkillRank', verbose_name='Stupeň')),
            ],
            options={
                'verbose_name': 'Dovednostní body',
                'verbose_name_plural': 'Dovednostní body',
            },
        ),
    ]
