# Generated by Django 2.2.4 on 2019-08-18 08:18

from django.db import migrations

from dictionary.models import skill


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_auto_20190818_1004'),
    ]

    operations = [
        migrations.RunPython(skill.init_skills),
    ]
