# Generated by Django 2.2.5 on 2019-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jméno', max_length=20, verbose_name='Jméno statu')),
                ('shortcut', models.CharField(default='BLK', max_length=3, verbose_name='Zkratka statu')),
            ],
        ),
    ]
