# Generated by Django 2.2.4 on 2019-08-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Obratnost'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Zkušenosti'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Inteligence'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Úroven'),
        ),
        migrations.AddField(
            model_name='character',
            name='resistance',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Odolnost'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Síla'),
        ),
    ]
