# Generated by Django 2.2.5 on 2019-10-26 13:24

from django.db import migrations

from base.models import stat


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_stat'),
    ]
    
    operations = [
        migrations.RunPython(stat.init_stats)
    ]
