# Generated by Django 2.2 on 2019-04-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20190420_1343'),
        ('base', '0002_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.BaseProfession'),
        ),
    ]
