# Generated by Django 2.2.8 on 2020-01-05 07:42

from django.db import migrations
import utils.models.color_field


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifuser',
            name='chat_color',
            field=utils.models.color_field.ColorField(default='#ffffff', max_length=10, verbose_name='Barva chatu'),
        ),
    ]
