# Generated by Django 2.2 on 2019-05-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190424_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifuser',
            name='active_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Character', verbose_name='Aktivní postava'),
        ),
    ]
