# Generated by Django 2.2.8 on 2020-02-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ifuser_chat_sounds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprofession',
            options={'ordering': ['parent_prof', 'name'], 'verbose_name': 'Povolání', 'verbose_name_plural': 'Povolání'},
        ),
        migrations.AlterModelOptions(
            name='creaturesize',
            options={'ordering': ['name'], 'verbose_name': 'Velikostní třída', 'verbose_name_plural': 'Velikostní třídy'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name'], 'verbose_name': 'Rasa', 'verbose_name_plural': 'Rasy'},
        ),
        migrations.AlterModelOptions(
            name='xplevel',
            options={'ordering': ['profession', 'level'], 'verbose_name': 'Úroveň', 'verbose_name_plural': 'Úrovně'},
        ),
    ]
