# Generated by Django 3.0.5 on 2020-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ifuser_chat_sounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=0, verbose_name='Životy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximální životy'),
            preserve_default=False,
        ),
    ]
