# Generated by Django 3.1 on 2020-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200511_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
